CREATE PROC FI_SP_ConsBeneficiario
	@ID BIGINT = NULL,
	@IDCLIENTE BIGINT = NULL
AS
BEGIN
	IF(ISNULL(@ID,0) = 0 AND ISNULL(@IDCLIENTE,0) = 0)
		SELECT NOME, CPF, IDCLIENTE, ID FROM BENEFICIARIOS WITH(NOLOCK)
	ELSE IF(ISNULL(@ID,0) > 0)
		SELECT NOME, CPF, IDCLIENTE, ID FROM BENEFICIARIOS WITH(NOLOCK) WHERE ID = @ID
	ELSE IF(ISNULL(@IDCLIENTE,0) > 0)
		SELECT NOME, CPF, IDCLIENTE, ID FROM BENEFICIARIOS WITH(NOLOCK) WHERE IDCLIENTE = @IDCLIENTE
END
